name: Sync UAT to Dev Branch

on:
  workflow_dispatch:
    inputs:
      release-branch:
        description: "masukin branch tolol"
        required: true
        default: "main"
  schedule:
    - cron: "*/40 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DEV repo
        uses: actions/checkout@v4

      - name: Add UAT remote
        run: |
          echo ${{ github.event.inputs.release-branch}}
          git remote add uat https://x-access-token:${{ secrets.UAT_TOKEN }}@github.com/ricokumalaa/commodity-landing-page.git
          git fetch uat

      - name: Mirror UAT main
        run: |
          git checkout -B mini-uat
          git reset --hard uat/main
          git push origin mini-uat --force
